import Head from 'next/head';
import Layout from '../layout/Layout';
import { SliderApp } from '../components/SliderApp/SliderApp';

export default function Home() {
    const sliderItems = [
        {
            id: '1',
            type: 'simple',
            bgImageUrl: '/pics/slider-1.gif',
            href: '/',
        },
        {
            id: '2',
            type: 'withContent',
            bgImageUrl: '/pics/slider-2.jpg',
            text: 'Feel the joy of your favourite running shoes in a luxe look.Meet the striking new PLATINUM Collection.',
            link: {
                url: '/shop',
                anchor: 'Shop now'
            }
        },
        {
            id: '3',
            type: 'simple',
            bgImageUrl: '/pics/slider-3.jpg'
        }
    ];

    return (
        <Layout>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            {sliderItems && <SliderApp items={sliderItems} />}
        </Layout>
    );
}
